[font]
normal = { family = "GoMono Nerd Font", style = "Regular" }
size = 15.0

# Window padding
[window]
padding = { x = 10, y = 10 }

[general]
import = ["~/.config/alacritty/themes/volgograd.toml"]

[env]
TERM = "xterm-256color"
